services:
  postgres:
    image: postgres:16-alpine
    container_name: snow_factory_db
    environment:
      POSTGRES_USER: snow_user
      POSTGRES_PASSWORD: snow_pass
      POSTGRES_DB: snow_factory
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U snow_user -d snow_factory"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
